### ISSUE TITLE
How do you get signed by mozilla?

### ISSUE THREAD

**Issue by KarlHegbloom** [slowphil/zotexmacs#1]
Please try my zotero-texmacs-integraton, which requires the propachi-texmacs xpi. How do I get that signed?

Also,  What do you think about adding the functionality to insert czcite from Juris-M / Zotero menu? It's a little redundant,  but maybe people will use it? 

What interactions with the editor and the document and zotero seem to belong on the Zotero side to initiate the action, vs on the editor side? 

Document management?  Template data? List of cites per document works now via trading in the integration interface. Please try it.

**Comment by KarlHegbloom** [comment]
Sorry,  but I don't have your direct email address. Can you put in the support for the zotero.scm to connect to zotero on windows,  please? I mean in the zotero-texmacs-integration I've done. I'm linking to your Windows builds from my README but they won't work yet. You'll see where when you fork,  clone,  branch,  fix,  and submit a pull-request, if you can.  I don't run Windows,  and need your help.

**Comment by slowphil** [comment]
Hi Karl,

> How do I get that signed?
 
 Short of a simple (and free) solution to sign it on my own, I had it
 signed by Mozilla which is clearly the easiest think to do. I don't
 remember exactly how I submitted it to them in February, but I'm sure
 that googleing it will bring you the answer ( that how I found how to do).
 
> Also, What do you think about adding the functionality to insert
> czcite from Juris-M / Zotero menu? It's a little redundant, but maybe
> people will use it?
 
 Frankly I did not try it because it seemed really complicated to get
 going and also -since you are not Joris who can "force" stuff to every
 one- I do not like the principle of changing the document tags
 themselves : it amounts to making a fork of TeXmacs which produces
 incompatible documents and I doubt that can get a lot of traction given
 the already small texmacs user base. Finally, my approach, while
 rudimentary, completely fulfills my needs (and Mozilla says there are
 ~12-15 people out there using it, which makes me very happy : ~1/3 of
 the 17000 firefox extensions do worse than that and you can't believe
 the number of those which have simply no users at all)
 
> What interactions with the editor and the document and zotero seem to
> belong on the Zotero side to initiate the action, vs on the editor side?
 
 Given the routes we have each taken, I guess not all people would agree
 on that...
 
> Document management? Template data? List of cites per document works
> now via trading in the integration interface. Please try it.
 
 Document management?: All of this is implemented in Zotero,
 re-implementing it -probably not as thoroughly- is redundant and thus
 does not seem a good idea to me. It is a bit the same I think of Joris'
 bibliographic database stuff : it's awkward, painfully slow and ...
 redundant!
 Template data?: what do you mean? Both TeXmacs and Zotero already have
 "templates" when you create a new document / zotero item, and zotero
 fills it in automatically from the web (at least for scientific articles
 like I use).
 List of cites per document : You mean per Zotero item? I do not produce
 that much articles that I cannot figure it out of my head! :)

Really, I think it is not Texmacs' core task do handle the bibliographic
database (and many other things) and we should delegate it as much as we
can.

Best,
Philippe-

**Comment by slowphil** [comment]
Le 26/07/2016 00:50, Karl Hegbloom - notifications@github.com a écrit :

> Sorry, but I don't have your direct email address. Can you put in the
> support for the zotero.scm to connect to zotero on windows, please? I
> mean in the zotero-texmacs-integration I've done. I'm linking to your
> Windows builds from my README but they won't work yet. You'll see
> where when you fork, clone, branch, fix, and submit a pull-request, if
> you can. I don't run Windows, and need your help.
 
 That address is okay. Like I said in the other answer, integrating your
 changes would make an incompatible fork of texmacs. Not what I want to
 do. The patches I apply keep the documents 100% compatible and are meant
 to be integrated in the svn trunk one day or another: they will
 eventually go away.

FYI I do not run windows personally neither at home nor at work
(although I have access to windows machines there and a vm at home).
I've been making such packages for years for my colleagues who run
windows and had no spell checker!

Best,
Philippe

**Comment by KarlHegbloom** [comment]
No changes to TeXmacs are required. The program comes with a style sheet
(tm-zotero.ts) that defines the macros that it uses.

**Comment by slowphil** [comment]
signing is no longer needed for zotero 5!
