### ISSUE TITLE
Server off by default and no preference widget

### ISSUE THREAD

**Issue by woutersj** [slowphil/zotexmacs#4]
After installing the plugin, the default seems to be to leave the server turned off. I see there is a preference widget, but I think it is not accessible yet?

For reference of others, this made the server start at the next TeXmacs startup:
`(set-boolean-preference "zotero-server" #t)`

**Comment by slowphil** [comment]
Ah yes, good catch, thanks. Sorry for the inconvenience and glad you could fix it.
I was figuring it would be quick and easy to get my patch for [plugins pref tabs](https://savannah.gnu.org/patch/?10177) in the trunk, but Joris is not in favor of that. I've incorporated it in my builds at Open Build Service (including in the AppImages), if you want...
In any case, I'll update the plugin so that when there is no preference tabs for plugins, this plugin's setting is accessible at the bottom of the "tools" menu (as Joris suggests).

**Comment by slowphil** [comment]
should be fixed now.

**Comment by woutersj** [comment]
Great, thanks a lot or the quick reply! This seems to work. Thanks for the nice plugin!
